-- 1. Drop PETSALE table
DROP TABLE PETSALE;

-- 2. Create PETSALE table 
CREATE TABLE PETSALE(
	ID INTEGER PRIMARY KEY NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	SALEPRICE DECIMAL(6,2),
	SALEDATE DATE);
	
-- 3. Insert data into PETSALE table
INSERT INTO PETSALE 
VALUES
(1,'Cat',9,450.09,'2018-05-29'),
(2,'Dog',3,666.66,'2018-06-01'),
(3,'Dog',1,100.00,'2018-06-04'),
(4,'Parrot',2,50.00,'2018-06-04'),
(5,'Dog',1,75.75,'2018-06-10'),
(6,'Hamster',6,60.60,'2018-06-11'),
(7,'Cat',1,44.44,'2018-06-11'),
(8,'Goldfish',24,48.48,'2018-06-14'),
(9,'Dog',2,222.22,'2018-06-15');

-- 4. Code
SELECT * FROM PETSALE;
SELECT SUM(SALEPRICE) FROM PETSALE;
SELECT SUM(SALEPRICE) AS SUM_OF_SALEPRICE FROM PETSALE;
SELECT MAX(QUANTITY) FROM PETSALE;
SELECT MIN(ID) FROM PETSALE WHERE ANIMAL='Dog';
SELECT AVG(SALEPRICE) FROM PETSALE;
SELECT AVG(SALEPRICE/QUANTITY) FROM PETSALE WHERE ANIMAL = 'Dog'
SELECT ROUND(SALEPRICE) FROM PETSALE;
SELECT LENGTH(ANIMAL) FROM PETSALE;
SELECT DISTINCT(ANIMAL), LENGTH(ANIMAL) FROM PETSALE;
SELECT UCASE(ANIMAL) FROM PETSALE;
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETSALE;
SELECT * FROM PETSALE WHERE LCASE(ANIMAL) = 'cat';
SELECT DAYS(SALEDATE) FROM PETSALE WHERE  LCASE(ANIMAL) = 'cat';
SELECT COUNT(*) FROM PETSALE WHERE MONTH(SALEDATE) = '06';
SELECT SALEDATE, (SALEDATE + 3 DAYS) FROM PETSALE;
SELECT SALEDATE, (CURRENT DATE - SALEDATE) FROM PETSALE;