-- Sub-queries and Nested Selects

-- 1. Sub-Select
SELECT * FROM EMPLOYEES
	WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- 2. Column Expression
SELECT EMP_ID, SALARY, (SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY FROM EMPLOYEES;

-- 3. Derived Tables or Tables Expressions
SELECT * FROM (SELECT EMP_ID, F_NAME, L_NAME, DEP_ID FROM EMPLOYEES) AS EMP4ALL

-- Working with Multiple Tables

-- 4. Sub-queries

SELECT * FROM EMPLOYEES 
	WHERE DEP_ID IN (SELECT DEPT_ID_DEP FROM DEPARTMENTS)

SELECT * FROM EMPLOYEES 
	WHERE DEP_ID IN (SELECT DEPT_ID_DEP FROM DEPARMENTS WHERE LOC_ID = 'L0002' );

SELECT DEPT_ID_DEP, DEP_NAME FROM DEPARTMENTS
	WHERE DEPT_ID_DEP IN (SELECT DEP_ID FROM EMPLOYEES WHERE SALARY > 70000);

-- 5. Implicit join

SELECT * FROM EMPLOYEES, DEPARTMENTS
	WHERE EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP; 

SELECT * FROM EMPLOYEES E, DEPARTMENTS D
	WHERE E.DEP_ID = D.DEPT_ID_DEP;

SELECT EMPLOYEES.EMP_ID, DEPARTMENTS.DEPT_NAME FROM EMPLOYEES E, DEPARMENTS D
	WHERE E.DEP_ID = D.DEPT_ID_DEP;

SELECT E.EMP_ID, D.DEPT_ID_DEP FROM EMPLOYEES E, DEPARTMENTS D
	WHERE E.DEP_ID = D.DEPT_ID_DEP;